# test.yml

#  Name of workflow
name: Test workflow

# When workflow is triggered 
on:
  pull_request:
    branches:
      - main

# Jobs to carry out
jobs:
  test:
    # Operating system to run job on
    runs-on: ubuntu-latest
    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1
      # Install NodeJS
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      # Run npm install and build on our code
      - run: npm install
      - run: npm run build --if-present
      # Run Test
      - name: Run tests
        run: npm run test
      # Show the result of the test
      - name: Show Status
        if: failure()
        run: echo "Test failed"
      - name: Show Status
        if: success()
        run: echo "Test successful"